# Generated by Django 3.2.3 on 2021-06-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
    ]
