# Generated by Django 3.2.3 on 2021-06-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20210606_1513'),
    ]

    operations = [
    ]
