# Generated by Django 3.2.3 on 2021-06-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_admin_document_label_project_signer'),
    ]

    operations = [
    ]
