# Generated by Django 3.2.3 on 2021-06-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_auto_20210606_1600'),
    ]

    operations = [
    ]
