# Generated by Django 3.2 on 2021-06-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_auto_20210606_1835'),
    ]

    operations = [
    ]
